static int counter <- 0;

semaphore mutex <- 1;
semaphore empty <- 2;
semaphore full <- 0;

process Producer(burst: 4, priority: 2, arrival: 0) {
    wait(empty);
    wait(mutex);
    counter <- counter + 1;
    post(mutex);
    post(full);
}

process Consumer(burst: 4, priority: 1, arrival: 0) {
    wait(full);
    wait(mutex);
    counter <- counter - 1;
    post(mutex);
    post(empty);
}

process Logger(burst: 2, priority: 3, arrival: 1) {
    wait(mutex);
    post(mutex);
}

system Sys1(processes: [Producer, Consumer, Logger], scheduler: PRIORITY);

run(Sys1);